# Generated by Django 5.2.17 on 2026-09-30 02:29

import arkray.identity.models
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('sales_user', 'Sales user')], default='sales_user', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'identity_user',
                'constraints': [models.CheckConstraint(condition=models.Q(('email', django.db.models.functions.text.Lower('email'))), name='identity_user_email_lowercase'), models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'sales_user'])), name='identity_user_role_valid'), models.CheckConstraint(condition=models.Q(('full_name', ''), _negated=True), name='identity_user_name_present')],
            },
            managers=[
                ('objects', arkray.identity.models.UserManager()),
            ],
        ),
    ]
