# Generated by Django 5.2.17 on 2026-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_account_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAccessWindow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('workspace', models.CharField(max_length=36)),
                ('window_start', models.DateTimeField()),
            ],
            options={
                'db_table': 'identity_workspace_access_window',
                'indexes': [models.Index(fields=['window_start'], name='workspace_access_window_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'workspace', 'window_start'), name='workspace_access_window_unique')],
            },
        ),
    ]
