# Generated by Django 5.2.17 on 2026-10-04 18:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from arkray.core.migrations._reverse_guard import RefuseReverse


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_workspace_access_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('session_digest', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('exited', 'Exited'), ('expired', 'Expired'), ('signed_out', 'Signed out'), ('not_allowed', 'No longer allowed'), ('session_changed', 'Browser session changed')], default='', max_length=16)),
                ('admin', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_support_session',
                'indexes': [models.Index(condition=models.Q(('ended_at__isnull', True)), fields=['expires_at'], name='identity_support_live_idx'), models.Index(fields=['target', '-started_at'], name='identity_support_target_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('admin', models.F('target')), _negated=True), name='identity_support_not_self'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('started_at'))), name='identity_support_expires_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('end_reason', ''), ('ended_at__isnull', True)), models.Q(('ended_at__isnull', False), ('end_reason__in', ['exited', 'expired', 'signed_out', 'not_allowed', 'session_changed'])), _connector='OR'), name='identity_support_end_complete'), models.CheckConstraint(condition=models.Q(('session_digest__regex', '^[0-9a-f]{64}$')), name='identity_support_digest_format'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('admin',), name='identity_support_one_live_per_admin')],
            },
        ),
        # Last, so it runs first when reversing (docs/deployment.md#rollback).
        RefuseReverse(
            'identity.0004_support_sessions',
            "the support sessions and the users' password-change state",
        ),
    ]
