# Generated by Django 5.2.17 on 2026-10-04 02:14

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0006_leads_autovacuum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # pgvector (the docker image and managed PostgreSQL offerings ship it). Kept on
        # rollback, like pg_trgm and btree_gin: other objects may come to depend on it.
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS vector', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workspace_kind', models.CharField(choices=[('self', 'Self'), ('user', 'User'), ('organization', 'Organization')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_conversation',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('lead', 'lead'), ('opportunity', 'opportunity'), ('task', 'task'), ('meeting', 'meeting'), ('note', 'note')], max_length=16)),
                ('source_id', models.UUIDField()),
                ('chunk_index', models.PositiveSmallIntegerField()),
                ('opportunity_id', models.UUIDField(blank=True, null=True)),
                ('source_hash', models.CharField(max_length=64)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('embedding_model', models.CharField(max_length=100)),
                ('source_updated_at', models.DateTimeField()),
                ('indexed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='leads.lead')),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_knowledge_chunk',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=40)),
                ('mode', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('actor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ai.conversation')),
            ],
            options={
                'db_table': 'ai_question',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['actor', 'workspace_kind', 'subject', '-updated_at'], name='ai_conversation_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='ai_conversation_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject__isnull', True), ('workspace_kind', 'organization')), models.Q(('subject', models.F('actor')), ('workspace_kind', 'self')), models.Q(('subject__isnull', False), ('workspace_kind', 'user'), models.Q(('subject', models.F('actor')), _negated=True)), _connector='OR'), name='ai_conversation_workspace_valid'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='ai_chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['owner', 'source_type'], name='ai_chunk_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['lead'], name='ai_chunk_lead_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'chunk_index'), name='ai_chunk_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gt', models.F('char_start'))), name='ai_chunk_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ['lead', 'opportunity', 'task', 'meeting', 'note'])), name='ai_chunk_source_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.CheckConstraint(condition=models.Q(('source_hash__regex', '^[0-9a-f]{64}$')), name='ai_chunk_hash_valid'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_question_conv_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(condition=models.Q(('status', 'pending')), fields=['actor'], name='ai_question_pending_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('status', 'pending')), models.Q(('finished_at__isnull', False), ('status__in', ['answered', 'failed'])), _connector='OR'), name='ai_question_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'failed'), ('error_code', ''), _connector='OR'), name='ai_question_error_only_when_failed'),
        ),
    ]
