# Generated by Django 5.2.17 on 2026-10-04 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conversation',
            name='ai_conversation_workspace_valid',
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('subject__isnull', True), ('workspace_kind', 'organization')), models.Q(('subject', models.F('actor')), ('subject__isnull', False), ('workspace_kind', 'self')), models.Q(('subject__isnull', False), ('workspace_kind', 'user'), models.Q(('subject', models.F('actor')), _negated=True)), _connector='OR'), name='ai_conversation_workspace_valid'),
        ),
    ]
