/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/api/v1/admin/users": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["admin_users_list"];
        readonly put?: never;
        readonly post: operations["admin_users_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/users/{user_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["admin_users_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch: operations["admin_users_partial_update"];
        readonly trace?: never;
    };
    readonly "/api/v1/admin/users/{user_id}/activate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["admin_users_activate_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/users/{user_id}/change-email": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["admin_users_change_email_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/users/{user_id}/deactivate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["admin_users_deactivate_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/admin/users/{user_id}/resend-invitation": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["admin_users_resend_invitation_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/assignees": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** @description Who CRM records can be assigned to (owner pickers). Active users only, by name. */
        readonly get: operations["assignees_list"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/csrf": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** @description Issue the CSRF cookie the SPA echoes in X-CSRFToken. */
        readonly get: operations["auth_csrf_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/invitations/accept": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["auth_invitations_accept_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/invitations/verify": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** @description Who a still-valid invitation link is for. POST so the secret never enters a URL. */
        readonly post: operations["auth_invitations_verify_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["auth_login_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** @description Ends the session. Idempotent: signing out without a session is a no-op. */
        readonly post: operations["auth_logout_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["auth_me_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/password-reset": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["auth_password_reset_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/password-reset/confirm": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["auth_password_reset_confirm_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/auth/password/change": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["auth_password_change_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/config/lead-options": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** @description Statuses, sources, ratings and country codes for lead forms and filters. */
        readonly get: operations["lead_options"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/config/pipelines": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** @description Pipelines and their stages (configuration, the same for everyone). */
        readonly get: operations["pipelines_list"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * @description Describe a workspace (whose CRM it is). Opening another user's workspace is
         *     authorised and audited by resolve_workspace; outside the caller's reach it is 404.
         */
        readonly get: operations["workspaces_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["leads_list"];
        readonly put?: never;
        readonly post: operations["leads_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["leads_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch: operations["leads_update"];
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}/archive": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["leads_archive"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}/assign": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * @description Reassign a lead (crm.assign_any). The response shows the lead as reassigned, even if
         *     it has thereby left the workspace it was reassigned from.
         */
        readonly post: operations["leads_assign"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}/convert": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * @description Convert a lead: create its opportunity and set the lead's status to Converted, in
         *     one transaction. Send an Idempotency-Key so a retried request can't convert twice.
         */
        readonly post: operations["leads_convert"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}/restore": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["leads_restore"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/{lead_id}/status": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["leads_change_status"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/leads/duplicates": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * @description Possible duplicates of the contact details being entered, within this workspace only
         *     (never a way to learn about leads the caller can't see). Advisory: nothing is blocked
         *     or merged.
         */
        readonly get: operations["leads_duplicates"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["opportunities_list"];
        readonly put?: never;
        readonly post: operations["opportunities_create"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities/{opportunity_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["opportunities_retrieve"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch: operations["opportunities_update"];
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities/{opportunity_id}/archive": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["opportunities_archive"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities/{opportunity_id}/history": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** @description Stage history, newest first (append-only; never editable). */
        readonly get: operations["opportunities_history"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities/{opportunity_id}/move": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * @description The one stage-transition operation (drag and drop and "Move to stage" alike):
         *     open stages, won, lost, and reopening a closed opportunity into an open stage.
         */
        readonly post: operations["opportunities_move"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/opportunities/{opportunity_id}/restore": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["opportunities_restore"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/pipeline-board": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * @description The Kanban board: every stage of one pipeline with its count, value, weighted value
         *     and at most `cards_per_stage` cards, plus the open-pipeline totals. Bounded whatever
         *     the number of opportunities; a column's `next` continues in the opportunities list.
         */
        readonly get: operations["pipeline_board"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/api/v1/workspaces/{workspace}/pipeline-summary": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * @description Pipeline value, weighted pipeline and the open count in this workspace: the
         *     authoritative figures (the dashboard shows exactly these).
         */
        readonly get: operations["pipeline_summary"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A user as administrators see it. Expects selectors.admin_user_* querysets. */
        readonly AdminUser: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly full_name: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly role_label: string;
            readonly status: components["schemas"]["StatusEnum"];
            readonly status_label: string;
            /** Format: date-time */
            readonly last_login: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly activated_at: string | null;
            /** Format: date-time */
            readonly deactivated_at: string | null;
            readonly invitation: components["schemas"]["InvitationState"] | null;
            readonly version: number;
        };
        /** @description One keyset-paginated page of users (follow `next` / `previous` as given). */
        readonly AdminUserPage: {
            readonly results: readonly components["schemas"]["AdminUser"][];
            readonly next: string | null;
            readonly previous: string | null;
        };
        /** @description A user CRM records can be assigned to (for owner pickers). */
        readonly Assignee: {
            /** Format: uuid */
            readonly id: string;
            readonly full_name: string;
            /** Format: email */
            readonly email: string;
        };
        readonly AssigneePage: {
            readonly results: readonly components["schemas"]["Assignee"][];
            readonly next: string | null;
            readonly previous: string | null;
        };
        readonly Board: {
            readonly pipeline: components["schemas"]["PipelineRef"];
            readonly currency: string;
            readonly totals: components["schemas"]["PipelineTotals"];
            readonly columns: readonly components["schemas"]["BoardColumn"][];
        };
        readonly BoardColumn: {
            readonly stage: components["schemas"]["Stage"];
            readonly count: number;
            /** Format: decimal */
            readonly total_value: string;
            /** Format: decimal */
            readonly weighted_value: string;
            readonly ordering: components["schemas"]["OrderingEnum"];
            readonly cards: readonly components["schemas"]["OpportunityCard"][];
            /** @description The opportunities list continuing after these cards (same stage, filters and order), or null when the column shows everything. */
            readonly next: string | null;
        };
        /**
         * @description * `open` - Open
         *     * `qualified` - Qualified
         *     * `unqualified` - Unqualified
         *     * `converted` - Converted
         * @enum {string}
         */
        readonly CategoryEnum: "open" | "qualified" | "unqualified" | "converted";
        readonly Conversion: {
            readonly lead: components["schemas"]["Lead"];
            readonly opportunity: components["schemas"]["Opportunity"];
        };
        readonly Detail: {
            readonly detail: string;
        };
        readonly EmailChangeRequest: {
            /** Format: email */
            readonly email: string;
            readonly version: number;
            readonly current_password?: string;
        };
        readonly InvitationAcceptRequest: {
            readonly token: string;
            readonly password: string;
        };
        readonly InvitationPreview: {
            /** Format: email */
            readonly email: string;
            readonly first_name: string;
        };
        readonly InvitationState: {
            /** Format: date-time */
            readonly expires_at: string;
            /** Format: date-time */
            readonly sent_at: string | null;
            readonly expired: boolean;
        };
        readonly InvitationTokenRequest: {
            readonly token: string;
        };
        /**
         * @description * `self` - self
         *     * `user` - user
         *     * `organization` - organization
         * @enum {string}
         */
        readonly KindEnum: "self" | "user" | "organization";
        readonly Lead: {
            /** Format: uuid */
            readonly id: string;
            readonly display_name: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly organization_name: string;
            readonly job_title: string;
            readonly email: string;
            readonly phone: string;
            readonly mobile: string;
            readonly status: components["schemas"]["StatusRef"];
            readonly source: components["schemas"]["SourceRef"] | null;
            readonly rating: (components["schemas"]["RatingEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly owner: components["schemas"]["UserRef"];
            /** Format: date-time */
            readonly last_contacted_at: string | null;
            /** Format: date-time */
            readonly archived_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly version: number;
            readonly alternate_phone: string;
            readonly address_line_1: string;
            readonly address_line_2: string;
            readonly city: string;
            readonly state: string;
            readonly postal_code: string;
            readonly country: string;
            readonly description: string;
            readonly created_by: components["schemas"]["UserRef"];
        };
        readonly LeadAssignRequest: {
            /** Format: uuid */
            readonly owner: string;
            readonly version: number;
        };
        readonly LeadConvertRequest: {
            readonly title: string;
            /** @description Amount in the organisation currency (INR), e.g. "1250000.00". */
            readonly value: string | number;
            /** @description A percentage (0-100). Omit (or null) to use the stage's default. */
            readonly probability?: (string | number) | null;
            /** Format: date */
            readonly expected_close_date?: string | null;
            readonly description?: string;
            /** @description The lead's current version. */
            readonly version: number;
            /** Format: uuid */
            readonly pipeline?: string;
            /** Format: uuid */
            readonly stage?: string;
        };
        /** @description Profile fields (all optional here; the services enforce what a lead needs). */
        readonly LeadCreateRequest: {
            readonly first_name?: string;
            readonly last_name?: string;
            readonly organization_name?: string;
            readonly job_title?: string;
            readonly email?: string;
            readonly phone?: string;
            readonly mobile?: string;
            readonly alternate_phone?: string;
            readonly address_line_1?: string;
            readonly address_line_2?: string;
            readonly city?: string;
            readonly state?: string;
            readonly postal_code?: string;
            /** @description ISO 3166-1 alpha-2 code, e.g. IN; empty for none. */
            readonly country?: string;
            /** @description A lead source key. */
            readonly source?: string | null;
            readonly rating?: (components["schemas"]["RatingEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            readonly last_contacted_at?: string | null;
            readonly description?: string;
            /** @description A lead status key; the default status if omitted. */
            readonly status?: string;
            /**
             * Format: uuid
             * @description Organisation-wide workspace only (required there, needs crm.assign_any).
             */
            readonly owner?: string;
        };
        readonly LeadDuplicate: {
            /** Format: uuid */
            readonly id: string;
            readonly display_name: string;
            readonly organization_name: string;
            readonly owner: components["schemas"]["UserRef"];
            /** Format: date-time */
            readonly archived_at: string | null;
            readonly matched_on: readonly components["schemas"]["MatchedOnEnum"][];
        };
        readonly LeadDuplicateList: {
            readonly results: readonly components["schemas"]["LeadDuplicate"][];
        };
        readonly LeadListItem: {
            /** Format: uuid */
            readonly id: string;
            readonly display_name: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly organization_name: string;
            readonly job_title: string;
            readonly email: string;
            readonly phone: string;
            readonly mobile: string;
            readonly status: components["schemas"]["StatusRef"];
            readonly source: components["schemas"]["SourceRef"] | null;
            readonly rating: (components["schemas"]["RatingEnum"] | components["schemas"]["NullEnum"]) | null;
            readonly owner: components["schemas"]["UserRef"];
            /** Format: date-time */
            readonly last_contacted_at: string | null;
            /** Format: date-time */
            readonly archived_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly version: number;
        };
        /**
         * @description Choices for lead forms and filters. Inactive statuses and sources are included (leads
         *     may still carry them) but only active ones may be chosen.
         */
        readonly LeadOptions: {
            readonly statuses: readonly components["schemas"]["LeadStatusOption"][];
            readonly sources: readonly components["schemas"]["LeadSourceOption"][];
            readonly ratings: readonly components["schemas"]["RatingOption"][];
            readonly countries: readonly string[];
        };
        /** @description One keyset-paginated page of leads (follow `next` / `previous` as given). */
        readonly LeadPage: {
            readonly results: readonly components["schemas"]["LeadListItem"][];
            readonly next: string | null;
            readonly previous: string | null;
        };
        readonly LeadRef: {
            /** Format: uuid */
            readonly id: string | null;
            readonly display_name?: string;
            readonly organization_name?: string;
            readonly restricted: boolean;
        };
        readonly LeadSourceOption: {
            readonly key: string;
            readonly name: string;
            readonly is_active: boolean;
        };
        readonly LeadStatusChangeRequest: {
            readonly status: string;
            readonly version: number;
        };
        readonly LeadStatusOption: {
            readonly key: string;
            readonly name: string;
            readonly category: components["schemas"]["CategoryEnum"];
            readonly is_active: boolean;
            readonly is_default: boolean;
        };
        readonly LeadVersionRequest: {
            readonly version: number;
        };
        readonly LoginRequest: {
            readonly email: string;
            readonly password: string;
        };
        /**
         * @description * `email` - email
         *     * `phone` - phone
         * @enum {string}
         */
        readonly MatchedOnEnum: "email" | "phone";
        /** @enum {unknown} */
        readonly NullEnum: null;
        readonly Opportunity: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly lead: components["schemas"]["LeadRef"];
            readonly owner: components["schemas"]["UserRef"];
            readonly status: components["schemas"]["StageCategoryEnum"];
            /** Format: decimal */
            readonly value: string;
            /** Format: decimal */
            readonly probability: string;
            readonly probability_overridden: boolean;
            /** Format: decimal */
            readonly weighted_value: string;
            /** Format: date */
            readonly expected_close_date: string | null;
            /** Format: date-time */
            readonly closed_at: string | null;
            /** Format: date-time */
            readonly archived_at: string | null;
            readonly version: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly pipeline: components["schemas"]["PipelineRef"];
            readonly stage: components["schemas"]["Stage"];
            readonly description: string;
            readonly lost_reason: string;
            readonly created_by: components["schemas"]["UserRef"];
        };
        /** @description A board card and a list row. */
        readonly OpportunityCard: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly lead: components["schemas"]["LeadRef"];
            readonly owner: components["schemas"]["UserRef"];
            /** Format: uuid */
            readonly stage_id: string;
            readonly status: components["schemas"]["StageCategoryEnum"];
            /** Format: decimal */
            readonly value: string;
            /** Format: decimal */
            readonly probability: string;
            readonly probability_overridden: boolean;
            /** Format: decimal */
            readonly weighted_value: string;
            /** Format: date */
            readonly expected_close_date: string | null;
            /** Format: date-time */
            readonly closed_at: string | null;
            /** Format: date-time */
            readonly archived_at: string | null;
            readonly version: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly OpportunityCreateRequest: {
            readonly title: string;
            /** @description Amount in the organisation currency (INR), e.g. "1250000.00". */
            readonly value: string | number;
            /** @description A percentage (0-100). Omit (or null) to use the stage's default. */
            readonly probability?: (string | number) | null;
            /** Format: date */
            readonly expected_close_date?: string | null;
            readonly description?: string;
            /**
             * Format: uuid
             * @description The lead (in this workspace) the opportunity is for.
             */
            readonly lead: string;
            /**
             * Format: uuid
             * @description The default pipeline if omitted.
             */
            readonly pipeline?: string;
            /**
             * Format: uuid
             * @description A stage of the pipeline; its first open stage if omitted.
             */
            readonly stage?: string;
            readonly lost_reason?: string;
        };
        readonly OpportunityMoveRequest: {
            /**
             * Format: uuid
             * @description An active stage of the opportunity's pipeline.
             */
            readonly stage: string;
            readonly version: number;
            /** @description Optional, only when moving to a lost stage. */
            readonly lost_reason?: string;
        };
        /** @description One keyset-paginated page of opportunities (follow `next` / `previous` as given). */
        readonly OpportunityPage: {
            readonly results: readonly components["schemas"]["OpportunityCard"][];
            readonly next: string | null;
            readonly previous: string | null;
        };
        readonly OpportunityVersionRequest: {
            readonly version: number;
        };
        /**
         * @description * `-closed_at` - -closed_at
         *     * `-created_at` - -created_at
         *     * `-updated_at` - -updated_at
         *     * `-value` - -value
         *     * `created_at` - created_at
         *     * `expected_close` - expected_close
         *     * `value` - value
         * @enum {string}
         */
        readonly OrderingEnum: "-closed_at" | "-created_at" | "-updated_at" | "-value" | "created_at" | "expected_close" | "value";
        readonly PasswordChangeRequest: {
            readonly current_password: string;
            readonly new_password: string;
        };
        readonly PasswordResetConfirmRequest: {
            readonly token: string;
            readonly new_password: string;
        };
        readonly PasswordResetRequestRequest: {
            readonly email: string;
        };
        /** @description Profile fields (all optional here; the services enforce what a lead needs). */
        readonly PatchedLeadUpdateRequest: {
            readonly first_name?: string;
            readonly last_name?: string;
            readonly organization_name?: string;
            readonly job_title?: string;
            readonly email?: string;
            readonly phone?: string;
            readonly mobile?: string;
            readonly alternate_phone?: string;
            readonly address_line_1?: string;
            readonly address_line_2?: string;
            readonly city?: string;
            readonly state?: string;
            readonly postal_code?: string;
            /** @description ISO 3166-1 alpha-2 code, e.g. IN; empty for none. */
            readonly country?: string;
            /** @description A lead source key. */
            readonly source?: string | null;
            readonly rating?: (components["schemas"]["RatingEnum"] | components["schemas"]["NullEnum"]) | null;
            /** Format: date-time */
            readonly last_contacted_at?: string | null;
            readonly description?: string;
            readonly version?: number;
        };
        readonly PatchedOpportunityUpdateRequest: {
            readonly version?: number;
            readonly title?: string;
            /** @description Amount in the organisation currency (INR), e.g. "1250000.00". */
            readonly value?: string | number;
            /** @description A percentage (0-100). Omit (or null) to use the stage's default. */
            readonly probability?: (string | number) | null;
            /** Format: date */
            readonly expected_close_date?: string | null;
            readonly description?: string;
            readonly lost_reason?: string;
        };
        readonly PatchedUserUpdateRequest: {
            readonly first_name?: string;
            readonly last_name?: string;
            readonly role?: components["schemas"]["RoleEnum"];
            readonly version?: number;
        };
        readonly Pipeline: {
            /** Format: uuid */
            readonly id: string;
            readonly key: string;
            readonly name: string;
            readonly is_default: boolean;
            readonly is_active: boolean;
            readonly stages: readonly components["schemas"]["Stage"][];
        };
        /**
         * @description Every pipeline with its stages in order (retired ones flagged): the board columns
         *     and the stage choices of every form come from here, never from hard-coded lists.
         */
        readonly PipelineList: {
            readonly results: readonly components["schemas"]["Pipeline"][];
        };
        readonly PipelineRef: {
            /** Format: uuid */
            readonly id: string;
            readonly key: string;
            readonly name: string;
        };
        readonly PipelineSummary: {
            readonly currency: string;
            readonly totals: components["schemas"]["PipelineTotals"];
        };
        /** @description Open opportunities only: won, lost and archived never count. */
        readonly PipelineTotals: {
            /**
             * Format: decimal
             * @description SUM(value) of open opportunities.
             */
            readonly pipeline_value: string;
            /**
             * Format: decimal
             * @description SUM(value x probability / 100) of open opportunities, rounded once.
             */
            readonly weighted_pipeline: string;
            readonly open_count: number;
        };
        /**
         * @description * `hot` - Hot
         *     * `warm` - Warm
         *     * `cold` - Cold
         * @enum {string}
         */
        readonly RatingEnum: "hot" | "warm" | "cold";
        readonly RatingOption: {
            readonly key: components["schemas"]["RatingEnum"];
            readonly name: string;
        };
        /**
         * @description * `admin` - Admin
         *     * `sales_user` - User
         * @enum {string}
         */
        readonly RoleEnum: "admin" | "sales_user";
        readonly SourceRef: {
            readonly key: string;
            readonly name: string;
        };
        readonly Stage: {
            /** Format: uuid */
            readonly id: string;
            readonly key: string;
            readonly name: string;
            readonly position: number;
            /** Format: decimal */
            readonly probability: string;
            readonly category: components["schemas"]["StageCategoryEnum"];
            readonly is_active: boolean;
        };
        /**
         * @description * `open` - Open
         *     * `won` - Won
         *     * `lost` - Lost
         * @enum {string}
         */
        readonly StageCategoryEnum: "open" | "won" | "lost";
        readonly StageHistory: {
            readonly id: number;
            /** Format: uuid */
            readonly from_stage_id: string | null;
            /** Format: uuid */
            readonly to_stage_id: string;
            readonly from_stage_name: string;
            readonly to_stage_name: string;
            readonly from_status: string;
            readonly to_status: components["schemas"]["StageCategoryEnum"];
            /** Format: decimal */
            readonly value: string;
            /** Format: decimal */
            readonly probability: string;
            readonly lost_reason: string;
            readonly actor: components["schemas"]["UserRef"];
            /** Format: date-time */
            readonly occurred_at: string;
        };
        readonly StageHistoryPage: {
            readonly results: readonly components["schemas"]["StageHistory"][];
            readonly next: string | null;
            readonly previous: string | null;
        };
        /**
         * @description * `invited` - Invited
         *     * `active` - Active
         *     * `deactivated` - Deactivated
         * @enum {string}
         */
        readonly StatusEnum: "invited" | "active" | "deactivated";
        readonly StatusRef: {
            readonly key: string;
            readonly name: string;
            readonly category: components["schemas"]["CategoryEnum"];
        };
        readonly UserCreateRequest: {
            readonly first_name: string;
            /** @default  */
            readonly last_name: string;
            /** Format: email */
            readonly email: string;
            readonly role: components["schemas"]["RoleEnum"];
        };
        readonly UserRef: {
            /** Format: uuid */
            readonly id: string;
            readonly full_name: string;
            readonly is_active: boolean;
        };
        /** @description The signed-in user (GET /auth/me and the sign-in response). */
        readonly Viewer: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly first_name: string;
            readonly last_name: string;
            readonly full_name: string;
            readonly role: components["schemas"]["RoleEnum"];
            readonly role_label: string;
            readonly capabilities: readonly string[];
        };
        readonly Workspace: {
            readonly kind: components["schemas"]["KindEnum"];
            readonly subject: components["schemas"]["WorkspaceSubject"] | null;
        };
        readonly WorkspaceSubject: {
            /** Format: uuid */
            readonly id: string;
            readonly full_name: string;
            readonly status: components["schemas"]["StatusEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly admin_users_list: {
        readonly parameters: {
            readonly query?: {
                readonly cursor?: string;
                readonly page_size?: number;
                readonly q?: string;
                /**
                 * @description * `admin` - Admin
                 *     * `sales_user` - User
                 */
                readonly role?: "admin" | "sales_user";
                /**
                 * @description * `invited` - Invited
                 *     * `active` - Active
                 *     * `deactivated` - Deactivated
                 */
                readonly status?: "invited" | "active" | "deactivated";
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUserPage"];
                };
            };
        };
    };
    readonly admin_users_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_partial_update: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["PatchedUserUpdateRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_activate_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_change_email_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["EmailChangeRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_deactivate_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly admin_users_resend_invitation_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly user_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AdminUser"];
                };
            };
        };
    };
    readonly assignees_list: {
        readonly parameters: {
            readonly query?: {
                readonly cursor?: string;
                readonly page_size?: number;
                readonly q?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AssigneePage"];
                };
            };
        };
    };
    readonly auth_csrf_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No response body */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly auth_invitations_accept_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvitationPreview"];
                };
            };
        };
    };
    readonly auth_invitations_verify_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["InvitationTokenRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["InvitationPreview"];
                };
            };
        };
    };
    readonly auth_login_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LoginRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    readonly auth_logout_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description No response body */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly auth_me_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Viewer"];
                };
            };
        };
    };
    readonly auth_password_reset_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        readonly responses: {
            readonly 202: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Detail"];
                };
            };
        };
    };
    readonly auth_password_reset_confirm_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        readonly responses: {
            /** @description No response body */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly auth_password_change_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["PasswordChangeRequest"];
            };
        };
        readonly responses: {
            /** @description No response body */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly lead_options: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LeadOptions"];
                };
            };
        };
    };
    readonly pipelines_list: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PipelineList"];
                };
            };
        };
    };
    readonly workspaces_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description No response body */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_list: {
        readonly parameters: {
            readonly query?: {
                readonly archived?: boolean;
                /** @description Inclusive, business time zone. */
                readonly created_from?: string;
                /** @description Inclusive, business time zone. */
                readonly created_to?: string;
                readonly cursor?: string;
                /**
                 * @description * `-created_at` - -created_at
                 *     * `-last_contacted_at` - -last_contacted_at
                 *     * `-updated_at` - -updated_at
                 *     * `created_at` - created_at
                 *     * `last_contacted_at` - last_contacted_at
                 *     * `name` - name
                 */
                readonly ordering?: "-created_at" | "-last_contacted_at" | "-updated_at" | "created_at" | "last_contacted_at" | "name";
                /** @description Organisation-wide workspace only. */
                readonly owner?: string;
                readonly page_size?: number;
                readonly q?: string;
                /**
                 * @description * `hot` - Hot
                 *     * `warm` - Warm
                 *     * `cold` - Cold
                 */
                readonly rating?: "hot" | "warm" | "cold";
                readonly source?: string;
                readonly status?: string;
            };
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LeadPage"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description A UUID chosen by the client. Repeating the same request with the same key within 24 hours returns the lead created the first time instead of a duplicate. */
                readonly "Idempotency-Key"?: string;
            };
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadCreateRequest"];
            };
        };
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_update: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["PatchedLeadUpdateRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_archive: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadVersionRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_assign: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadAssignRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_convert: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description A UUID chosen by the client. Repeating the same request with the same key within 24 hours returns the lead created the first time instead of a duplicate. */
                readonly "Idempotency-Key"?: string;
            };
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadConvertRequest"];
            };
        };
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Conversion"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_restore: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadVersionRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_change_status: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly lead_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LeadStatusChangeRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly leads_duplicates: {
        readonly parameters: {
            readonly query?: {
                readonly email?: string;
                /** @description A lead to leave out (when editing). */
                readonly exclude?: string;
                readonly phone?: readonly string[];
            };
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["LeadDuplicateList"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_list: {
        readonly parameters: {
            readonly query?: {
                readonly archived?: boolean;
                readonly cursor?: string;
                /** @description Inclusive. */
                readonly expected_close_from?: string;
                /** @description Inclusive. */
                readonly expected_close_to?: string;
                readonly lead?: string;
                /**
                 * @description * `-closed_at` - -closed_at
                 *     * `-created_at` - -created_at
                 *     * `-updated_at` - -updated_at
                 *     * `-value` - -value
                 *     * `created_at` - created_at
                 *     * `expected_close` - expected_close
                 *     * `value` - value
                 */
                readonly ordering?: "-closed_at" | "-created_at" | "-updated_at" | "-value" | "created_at" | "expected_close" | "value";
                /** @description Organisation-wide workspace only. */
                readonly owner?: string;
                readonly page_size?: number;
                readonly pipeline?: string;
                readonly probability_max?: string | number;
                readonly probability_min?: string | number;
                readonly stage?: string;
                /**
                 * @description * `open` - Open
                 *     * `won` - Won
                 *     * `lost` - Lost
                 */
                readonly status?: "open" | "won" | "lost";
            };
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OpportunityPage"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_create: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description A UUID chosen by the client. Repeating the same request with the same key within 24 hours returns the lead created the first time instead of a duplicate. */
                readonly "Idempotency-Key"?: string;
            };
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OpportunityCreateRequest"];
            };
        };
        readonly responses: {
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_retrieve: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_update: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: {
            readonly content: {
                readonly "application/json": components["schemas"]["PatchedOpportunityUpdateRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_archive: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OpportunityVersionRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_history: {
        readonly parameters: {
            readonly query?: {
                readonly cursor?: string;
                readonly page_size?: number;
            };
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["StageHistoryPage"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_move: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OpportunityMoveRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly opportunities_restore: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly opportunity_id: string;
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["OpportunityVersionRequest"];
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Opportunity"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly pipeline_board: {
        readonly parameters: {
            readonly query?: {
                readonly cards_per_stage?: number;
                /** @description Inclusive. */
                readonly expected_close_from?: string;
                /** @description Inclusive. */
                readonly expected_close_to?: string;
                readonly lead?: string;
                /** @description Organisation-wide workspace only. */
                readonly owner?: string;
                /** @description The default pipeline if omitted. */
                readonly pipeline?: string;
                readonly probability_max?: string | number;
                readonly probability_min?: string | number;
            };
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Board"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly pipeline_summary: {
        readonly parameters: {
            readonly query?: {
                /** @description Inclusive. */
                readonly expected_close_from?: string;
                /** @description Inclusive. */
                readonly expected_close_to?: string;
                readonly lead?: string;
                /** @description Organisation-wide workspace only. */
                readonly owner?: string;
                /** @description Every pipeline if omitted. */
                readonly pipeline?: string;
                readonly probability_max?: string | number;
                readonly probability_min?: string | number;
            };
            readonly header?: never;
            readonly path: {
                readonly workspace: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PipelineSummary"];
                };
            };
            /** @description Not found, or outside this workspace. */
            readonly 404: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
