# Generated by Django 5.2.17 on 2026-09-30 10:41. The composite foreign keys and the history
# trigger, which Django cannot declare, are added by 0002_integrity.

import datetime
import django.db.models.constraints
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_id_owner_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pipeline_pipeline',
                'constraints': [models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]{0,31}$')), name='pipeline_pipeline_key_format'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pipeline_pipeline_name_present'), models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='pipeline_pipeline_default_is_active'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='pipeline_pipeline_one_default')],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
                ('position', models.PositiveSmallIntegerField()),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('pipeline', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='pipeline.pipeline')),
            ],
            options={
                'db_table': 'pipeline_stage',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('probability_overridden', models.BooleanField(default=False)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=5000)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=500)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('open_owner_id', models.GeneratedField(db_persist=True, expression=models.Case(models.When(status='open', then=models.F('owner_id')), default=None), output_field=models.UUIDField(null=True))),
                ('expected_close_sort', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('expected_close_date'), models.Value(datetime.date(9999, 12, 31))), output_field=models.DateField())),
                ('closed_sort', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('closed_at'), models.Value(datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))), output_field=models.DateTimeField())),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.lead')),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pipeline', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.pipeline')),
                ('stage', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.stage')),
            ],
            options={
                'db_table': 'pipeline_opportunity',
            },
        ),
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_stage_name', models.CharField(blank=True, default='', max_length=50)),
                ('to_stage_name', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, default='', max_length=8)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lost_reason', models.CharField(blank=True, default='', max_length=500)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_stage', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.stage')),
                ('opportunity', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.opportunity')),
                ('to_stage', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.stage')),
            ],
            options={
                'db_table': 'pipeline_stage_history',
            },
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]{0,31}$')), name='pipeline_stage_key_format'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='pipeline_stage_name_present'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['open', 'won', 'lost'])), name='pipeline_stage_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', Decimal('0')), ('probability__lte', Decimal('100'))), name='pipeline_stage_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'won'), _negated=True), ('probability', Decimal('100')), _connector='OR'), name='pipeline_stage_won_is_certain'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category', 'lost'), _negated=True), ('probability', Decimal('0')), _connector='OR'), name='pipeline_stage_lost_is_impossible'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'key'), name='pipeline_stage_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('pipeline', 'position'), name='pipeline_stage_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(models.F('pipeline'), django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='pipeline_stage_active_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='stage',
            constraint=models.UniqueConstraint(fields=('id', 'pipeline', 'category'), name='pipeline_stage_category_key'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('owner'), models.F('stage'), models.F('expected_close_sort'), models.F('created_at'), models.F('id'), condition=models.Q(('archived_at__isnull', True), ('status', 'open')), name='pipeline_opp_owner_open_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('owner'), models.F('stage'), models.OrderBy(models.F('closed_sort'), descending=True), models.OrderBy(models.F('id'), descending=True), condition=models.Q(models.Q(('status', 'open'), _negated=True), ('archived_at__isnull', True)), name='pipeline_opp_owner_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('stage'), models.F('expected_close_sort'), models.F('created_at'), models.F('id'), condition=models.Q(('archived_at__isnull', True), ('status', 'open')), name='pipeline_opp_open_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('stage'), models.OrderBy(models.F('closed_sort'), descending=True), models.OrderBy(models.F('id'), descending=True), condition=models.Q(models.Q(('status', 'open'), _negated=True), ('archived_at__isnull', True)), name='pipeline_opp_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('lead'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='pipeline_opp_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.F('owner'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='pipeline_opp_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='pipeline_opp_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='pipeline_opp_title_present'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'won', 'lost'])), name='pipeline_opp_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', Decimal('0'))), name='pipeline_opp_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability__gte', Decimal('0')), ('probability__lte', Decimal('100'))), name='pipeline_opp_probability_range'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'won'), _negated=True), ('probability', Decimal('100')), _connector='OR'), name='pipeline_opp_won_is_certain'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'lost'), _negated=True), ('probability', Decimal('0')), _connector='OR'), name='pipeline_opp_lost_is_impossible'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('closed_at__isnull', True), ('status', 'open')), models.Q(models.Q(('status', 'open'), _negated=True), ('closed_at__isnull', False)), _connector='OR'), name='pipeline_opp_closed_at_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('probability_overridden', False), ('status', 'open'), _connector='OR'), name='pipeline_opp_override_only_while_open'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('lost_reason', ''), ('status', 'lost'), _connector='OR'), name='pipeline_opp_lost_reason_only_when_lost'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('expected_close_date__isnull', True), ('expected_close_date__range', (datetime.date(2000, 1, 1), datetime.date(2099, 12, 31))), _connector='OR'), name='pipeline_opp_expected_close_range'),
        ),
        migrations.AddConstraint(
            model_name='opportunity',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='pipeline_opp_version_positive'),
        ),
        migrations.AddIndex(
            model_name='stagehistory',
            index=models.Index(models.F('opportunity'), models.OrderBy(models.F('occurred_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='pipeline_history_opp_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagehistory',
            constraint=models.CheckConstraint(condition=models.Q(('to_status__in', ['open', 'won', 'lost'])), name='pipeline_history_to_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='stagehistory',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_stage__isnull', True), ('from_stage_name', ''), ('from_status', '')), models.Q(('from_stage__isnull', False), ('from_status__in', ['open', 'won', 'lost']), models.Q(('from_stage_name', ''), _negated=True)), _connector='OR'), name='pipeline_history_from_complete'),
        ),
        migrations.AddConstraint(
            model_name='stagehistory',
            constraint=models.CheckConstraint(condition=models.Q(('lost_reason', ''), ('to_status', 'lost'), _connector='OR'), name='pipeline_history_lost_reason_only_when_lost'),
        ),
    ]
