# Phase 7: global search matches an opportunity's title (pipeline.models.SEARCH_TEXT) with a
# case-insensitive substring; this trigram index serves it in every workspace
# (docs/search.md#indexes has the plans before and after).
#
# Built CONCURRENTLY, so opportunity reads and writes go on throughout (a plain CREATE INDEX
# holds a SHARE lock: every write on the table would wait for the whole build). CONCURRENTLY
# can't run in a transaction, so the migration isn't atomic and lifts the timeouts for its
# session (not SET LOCAL): the statement timeout because the build reads the whole table, the
# lock timeout because the concurrent steps wait for older transactions without blocking
# anyone. Both are restored at the end, in either direction (as leads.0005).
# Generated by Django 5.2.17 on 2026-10-03 18:04

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

LIFT = "SET statement_timeout = 0; SET lock_timeout = 0;"
RESTORE = "RESET statement_timeout; RESET lock_timeout;"


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('leads', '0006_leads_autovacuum'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql=LIFT, reverse_sql=RESTORE),
        AddIndexConcurrently(
            model_name='opportunity',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), condition=models.Q(('archived_at__isnull', True)), name='pipeline_opp_search_trgm'),
        ),
        migrations.RunSQL(sql=RESTORE, reverse_sql=LIFT),
    ]
