# Generated by Django 5.2.17 on 2026-09-30 07:28

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # pg_trgm (for the search index) is created by identity.0002.
        ("identity", "0002_account_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'leads_lead_source',
                'constraints': [models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]{0,31}$')), name='leads_lead_source_key_format'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='leads_lead_source_name_present')],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('open', 'Open'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], max_length=16)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'leads_lead_status',
                'constraints': [models.CheckConstraint(condition=models.Q(('key__regex', '^[a-z][a-z0-9_]{0,31}$')), name='leads_lead_status_key_format'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='leads_lead_status_name_present'), models.CheckConstraint(condition=models.Q(('category__in', ['open', 'qualified', 'unqualified', 'converted'])), name='leads_lead_status_category_valid'), models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='leads_lead_status_default_is_active'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='leads_lead_status_one_default')],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('organization_name', models.CharField(blank=True, default='', max_length=200)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.CharField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('mobile', models.CharField(blank=True, default='', max_length=32)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=32)),
                ('phone_keys', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('country', models.CharField(blank=True, default='', max_length=2)),
                ('rating', models.CharField(blank=True, choices=[('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold')], max_length=8, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=5000)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('display_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.NullIf(django.db.models.functions.text.Trim(django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name'))), models.Value('')), models.F('organization_name')), output_field=models.CharField(max_length=201))),
                ('search_text', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper(django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name'), models.Value(' '), models.F('organization_name'), models.Value(' '), models.F('email'), models.Value(' '), models.Func(models.F('phone'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'), models.Value(' '), models.Func(models.F('mobile'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'), models.Value(' '), models.Func(models.F('alternate_phone'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'))), output_field=models.TextField())),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, db_column='source_key', db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.leadsource', to_field='key')),
                ('status', models.ForeignKey(db_column='status_key', db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.leadstatus', to_field='key')),
            ],
            options={
                'db_table': 'leads_lead',
                'indexes': [models.Index(models.F('owner'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_owner_created_idx'), models.Index(models.F('owner'), models.OrderBy(models.F('updated_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_owner_updated_idx'), models.Index(models.F('owner'), models.OrderBy(models.F('last_contacted_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='leads_owner_contacted_idx'), models.Index(models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_created_idx'), models.Index(models.F('display_name'), models.F('id'), name='leads_name_idx'), models.Index(models.OrderBy(models.F('updated_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_updated_idx'), models.Index(models.OrderBy(models.F('last_contacted_at'), descending=True, nulls_last=True), models.OrderBy(models.F('id'), descending=True), name='leads_contacted_idx'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('search_text'), name='gin_trgm_ops'), name='leads_search_trgm'), models.Index(django.db.models.functions.text.Lower('email'), condition=models.Q(('email', ''), _negated=True), name='leads_email_lower_idx'), django.contrib.postgres.indexes.GinIndex(models.F('phone_keys'), name='leads_phone_keys_gin')],
                'constraints': [models.CheckConstraint(condition=models.Q(('first_name', ''), ('last_name', ''), ('organization_name', ''), _negated=True), name='leads_lead_name_present'), models.CheckConstraint(condition=models.Q(('rating__isnull', True), ('rating__in', ['hot', 'warm', 'cold']), _connector='OR'), name='leads_lead_rating_valid'), models.CheckConstraint(condition=models.Q(('country', ''), ('country__regex', '^[A-Z]{2}$'), _connector='OR'), name='leads_lead_country_format'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='leads_lead_version_positive'), models.CheckConstraint(condition=models.Q(('updated_at__gte', models.F('created_at'))), name='leads_lead_updated_after_created')],
            },
        ),
    ]
