# Generated by Django 5.2.17 on 2026-09-30 08:27, then edited: PostgreSQL can't change the
# type of a column that a generated column reads, so `search_text` (and its trigram index)
# is dropped before the phone columns are widened and re-created, unchanged, afterwards.

import datetime

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_seed_statuses_and_sources'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='leads_lead_updated_after_created',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_owner_contacted_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_contacted_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_sort',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('last_contacted_at'), models.Value(datetime.datetime(1900, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))), output_field=models.DateTimeField()),
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_search_trgm',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='search_text',
        ),
        migrations.AlterField(
            model_name='lead',
            name='alternate_phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='lead',
            name='search_text',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Upper(django.db.models.functions.text.Concat(models.F('first_name'), models.Value(' '), models.F('last_name'), models.Value(' '), models.F('organization_name'), models.Value(' '), models.F('email'), models.Value(' '), models.Func(models.F('phone'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'), models.Value(' '), models.Func(models.F('mobile'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'), models.Value(' '), models.Func(models.F('alternate_phone'), models.Value('[^0-9]'), models.Value(''), models.Value('g'), function='regexp_replace'))), output_field=models.TextField()),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(models.F('search_text'), name='gin_trgm_ops'), name='leads_search_trgm'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(models.F('owner'), models.OrderBy(models.F('last_contacted_sort'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_owner_contacted_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(models.F('owner'), models.F('display_name'), models.F('id'), name='leads_owner_name_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(models.OrderBy(models.F('last_contacted_sort'), descending=True), models.OrderBy(models.F('id'), descending=True), name='leads_contacted_idx'),
        ),
    ]
