# Generated by Django 5.2.17 on 2026-09-30 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_review_hardening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('id', 'owner'), name='leads_lead_id_owner_key'),
        ),
    ]
