# Phase 5: the per-owner lead index carries the archive state, so the dashboard's lead figures
# are counted from the index alone (docs/dashboard.md#performance). Same name, key columns and
# order as before: every list plan that used it still does.
#
# Built and swapped without blocking anyone (Phase 5 review): the new index is created
# CONCURRENTLY under a temporary name, the old one dropped CONCURRENTLY, then the new one
# renamed (ALTER INDEX RENAME takes only SHARE UPDATE EXCLUSIVE). Lead reads and writes go on
# throughout; a plain DROP INDEX would need ACCESS EXCLUSIVE on leads_lead, so one long
# reader could stall every lead request for the lock timeout and fail the deploy.
#
# CONCURRENTLY can't run in a transaction, so the migration isn't atomic and lifts the
# timeouts for its session (not SET LOCAL): the statement timeout because the build reads the
# whole table, the lock timeout because the concurrent steps wait for older transactions
# without blocking anyone. Both are restored at the end, in either direction.
# Generated by Django 5.2.17 on 2026-10-03 11:02

from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently, RemoveIndexConcurrently
from django.db import migrations, models

LIFT = "SET statement_timeout = 0; SET lock_timeout = 0;"
RESTORE = "RESET statement_timeout; RESET lock_timeout;"


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('leads', '0004_id_owner_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql=LIFT, reverse_sql=RESTORE),
        AddIndexConcurrently(
            model_name='lead',
            index=models.Index(models.F('owner'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), include=('archived_at',), name='leads_owner_created_new'),
        ),
        RemoveIndexConcurrently(
            model_name='lead',
            name='leads_owner_created_idx',
        ),
        migrations.RenameIndex(
            model_name='lead',
            new_name='leads_owner_created_idx',
            old_name='leads_owner_created_new',
        ),
        migrations.RunSQL(sql=RESTORE, reverse_sql=LIFT),
    ]
