# Generated by Django 5.2.17 on 2026-09-30 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System')], max_length=16)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('subject_user_id', models.UUIDField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'audit_event',
                'indexes': [models.Index(fields=['-occurred_at'], name='audit_occurred_idx'), models.Index(fields=['actor_id', '-occurred_at'], name='audit_actor_idx'), models.Index(fields=['subject_user_id', '-occurred_at'], name='audit_subject_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_target_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_action_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('actor_type__in', ['user', 'system'])), name='audit_actor_type_valid'), models.CheckConstraint(condition=models.Q(('actor_type', 'system'), ('actor_id__isnull', False), _connector='OR'), name='audit_user_actor_has_id')],
            },
        ),
    ]
