# Generated by Django 5.2.17 on 2026-10-10 14:39

import django.db.models.deletion
from django.db import migrations, models

from arkray.core.migrations._reverse_guard import RefuseReverse


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0004_support_session_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditevent",
            name="detail_digest",
            field=models.CharField(blank=True, db_default="", default="", max_length=64),
        ),
        migrations.CreateModel(
            name="AuditDetail",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detail",
                        serialize=False,
                        to="audit.auditevent",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("values", models.JSONField(blank=True, default=dict)),
                ("salt", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "audit_event_detail",
                "indexes": [models.Index(fields=["expires_at"], name="audit_detail_expires_idx")],
            },
        ),
        RefuseReverse(
            "audit.0005_audit_details",
            loses="audit events' expiring personal details (client addresses, old and new emails, support reasons)",
        ),
    ]
