# Generated by Django 5.2.17 on 2026-09-30 02:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('queue', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('done', 'Done'), ('dead', 'Dead (needs attention)')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('correlation_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_outbox_event',
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['queue', 'available_at'], name='outbox_pending_due_idx'), models.Index(condition=models.Q(('status', 'in_flight')), fields=['queue', 'locked_until'], name='outbox_in_flight_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('dedupe_key', ''), _negated=True)), fields=('topic', 'dedupe_key'), name='outbox_pending_dedupe_uniq'), models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'in_flight', 'done', 'dead'])), name='outbox_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'in_flight'), _negated=True), ('locked_until__isnull', False), _connector='OR'), name='outbox_in_flight_has_lease'), models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ['done', 'dead'])), models.Q(('finished_at', None), ('status__in', ['pending', 'in_flight'])), _connector='OR'), name='outbox_finished_at_matches_status')],
            },
        ),
    ]
