# Generated by Django 5.2.17 on 2026-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forbid_mutation_function'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='outboxevent',
            name='outbox_pending_dedupe_uniq',
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='claim_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(condition=models.Q(('attempts', 0), ('status', 'pending'), models.Q(('dedupe_key', ''), _negated=True)), fields=['topic', 'dedupe_key'], name='outbox_coalesce_idx'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'in_flight'), _negated=True), ('claim_token__isnull', False), _connector='OR'), name='outbox_in_flight_has_claim'),
        ),
    ]
