# Generated by Django 5.2.17 on 2026-09-30 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_outbox_claim_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor_id', models.UUIDField()),
                ('operation', models.CharField(max_length=64)),
                ('key', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('resource_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'core_idempotency_record',
                'constraints': [models.UniqueConstraint(fields=('actor_id', 'operation', 'key'), name='core_idempotency_unique_key'), models.CheckConstraint(condition=models.Q(('request_hash__regex', '^[0-9a-f]{64}$')), name='core_idempotency_hash_format')],
            },
        ),
    ]
