# Generated by Django 5.2.17 on 2026-10-10 15:11

import django.utils.timezone
import uuid
from django.db import migrations, models

from arkray.core.migrations._reverse_guard import RefuseReverse


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_outbox_dead_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('applied_seq', models.BigIntegerField(default=0)),
                ('applied_mac', models.CharField(blank=True, default='', max_length=64)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'core_erasure_ledger_state',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='core_ledger_state_single_row'), models.CheckConstraint(condition=models.Q(('applied_seq__gte', 0)), name='core_ledger_state_seq')],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('lead', 'Lead (customer)'), ('user', 'User (staff)')], max_length=8)),
                ('subject_id', models.UUIDField()),
                ('reference', models.CharField(max_length=64)),
                ('placed_by', models.UUIDField()),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_by', models.UUIDField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_legal_hold',
                'constraints': [models.CheckConstraint(condition=models.Q(('subject_type__in', ['lead', 'user'])), name='core_legal_hold_subject'), models.CheckConstraint(condition=models.Q(('reference', ''), _negated=True), name='core_legal_hold_reference_present'), models.CheckConstraint(condition=models.Q(models.Q(('released_at__isnull', True), ('released_by__isnull', True)), models.Q(('released_at__isnull', False), ('released_by__isnull', False)), _connector='OR'), name='core_legal_hold_release_complete'), models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('subject_type', 'subject_id'), name='core_legal_hold_one_active')],
            },
        ),
        RefuseReverse(
            "core.0006_privacy_remediation",
            loses="legal holds and how far the database has applied the erasure ledger",
        ),
    ]
