# Generated by Django 5.2.17 on 2026-10-03 07:58

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.text
import django.db.models.lookups
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0004_id_owner_key'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('task', 'Task'), ('meeting', 'Meeting'), ('note', 'Note')], max_length=16)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('open', 'Open'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=16, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], max_length=8, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('meeting_url', models.CharField(blank=True, default='', max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('current_owner_id', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.F('owner_id'), type='note'), models.When(status__in=('open', 'scheduled'), then=models.F('owner_id')), default=None), output_field=models.UUIDField(null=True))),
                ('schedule_sort', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=django.db.models.functions.comparison.Coalesce(models.F('due_at'), models.Value(datetime.datetime(9999, 12, 31, 0, 0, tzinfo=datetime.timezone.utc))), type='task'), models.When(then=models.F('starts_at'), type='meeting'), default=models.F('created_at'), output_field=models.DateTimeField()), output_field=models.DateTimeField())),
                ('cancelled_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.lead')),
                ('opportunity', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.opportunity')),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities_activity',
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('lead.created', 'Lead created'), ('lead.status_changed', 'Lead status changed'), ('lead.reassigned', 'Lead reassigned'), ('lead.archived', 'Lead archived'), ('lead.restored', 'Lead restored'), ('opportunity.created', 'Opportunity created'), ('opportunity.stage_changed', 'Opportunity stage changed'), ('opportunity.won', 'Opportunity won'), ('opportunity.lost', 'Opportunity lost'), ('opportunity.reopened', 'Opportunity reopened'), ('task.created', 'Task created'), ('task.completed', 'Task completed'), ('task.cancelled', 'Task cancelled'), ('task.reopened', 'Task reopened'), ('meeting.scheduled', 'Meeting scheduled'), ('meeting.rescheduled', 'Meeting rescheduled'), ('meeting.completed', 'Meeting completed'), ('meeting.cancelled', 'Meeting cancelled'), ('meeting.reopened', 'Meeting reopened'), ('note.added', 'Note added')], max_length=40)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('activity', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='activities.activity')),
                ('actor', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='leads.lead')),
                ('opportunity', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='pipeline.opportunity')),
            ],
            options={
                'db_table': 'activities_timeline_entry',
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('owner'), models.F('type'), models.F('status'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_owner_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('owner'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='activities_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('type'), models.F('status'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_sched_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='activities_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('lead'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='activities_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('opportunity'), models.OrderBy(models.F('created_at'), descending=True), models.OrderBy(models.F('id'), descending=True), condition=models.Q(('opportunity__isnull', False)), name='activities_opportunity_idx'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['task', 'meeting', 'note'])), name='activities_activity_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ('open', 'completed', 'cancelled')), ('status__isnull', False), ('type', 'task')), models.Q(('status__in', ('scheduled', 'completed', 'cancelled')), ('status__isnull', False), ('type', 'meeting')), models.Q(('status__isnull', True), ('type', 'note')), _connector='OR'), name='activities_activity_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('priority__in', ['low', 'normal', 'high']), ('priority__isnull', False), ('type', 'task')), models.Q(models.Q(('type', 'task'), _negated=True), ('priority__isnull', True)), _connector='OR'), name='activities_activity_priority_only_tasks'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('title', ''), ('type', 'note')), models.Q(models.Q(('type', 'note'), _negated=True), models.Q(('title', ''), _negated=True)), _connector='OR'), name='activities_activity_title_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'note'), _negated=True), models.Q(('description', ''), _negated=True), _connector='OR'), name='activities_activity_note_has_body'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(django.db.models.functions.text.Length('description'), 10000), name='activities_activity_description_length'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'task'), ('due_at__isnull', True), _connector='OR'), name='activities_activity_due_only_tasks'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('due_at__isnull', True), models.Q(('due_at__gte', datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)), ('due_at__lt', datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))), _connector='OR'), name='activities_activity_due_range'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_at__gt', models.F('starts_at')), ('ends_at__isnull', False), ('ends_at__lte', django.db.models.expressions.CombinedExpression(models.F('starts_at'), '+', models.Value(datetime.timedelta(days=1)))), ('starts_at__isnull', False), ('type', 'meeting')), models.Q(models.Q(('type', 'meeting'), _negated=True), ('ends_at__isnull', True), ('starts_at__isnull', True)), _connector='OR'), name='activities_activity_meeting_times'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), models.Q(('starts_at__gte', datetime.datetime(2000, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)), ('starts_at__lt', datetime.datetime(2100, 1, 1, 0, 0, tzinfo=datetime.timezone.utc))), _connector='OR'), name='activities_activity_starts_range'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('type', 'meeting'), models.Q(('location', ''), ('meeting_url', '')), _connector='OR'), name='activities_activity_place_only_meetings'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('meeting_url', ''), ('meeting_url__startswith', 'https://'), _connector='OR'), name='activities_activity_meeting_url_https'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('completed_by__isnull', False), ('status', 'completed'), ('status__isnull', False)), models.Q(models.Q(('status', 'completed'), _negated=True), ('completed_at__isnull', True), ('completed_by__isnull', True)), _connector='OR'), name='activities_activity_completed_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled'), ('status__isnull', False)), models.Q(models.Q(('status', 'cancelled'), _negated=True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True)), _connector='OR'), name='activities_activity_cancelled_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='activities_activity_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('schedule_sort__isnull', False)), name='activities_activity_schedule_sort_present'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('id', 'lead'), name='activities_activity_id_lead_key'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(models.F('lead'), models.OrderBy(models.F('occurred_at'), descending=True), models.OrderBy(models.F('id'), descending=True), name='timeline_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(models.F('opportunity'), models.OrderBy(models.F('occurred_at'), descending=True), models.OrderBy(models.F('id'), descending=True), condition=models.Q(('opportunity__isnull', False)), name='timeline_opportunity_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['lead.created', 'lead.status_changed', 'lead.reassigned', 'lead.archived', 'lead.restored', 'opportunity.created', 'opportunity.stage_changed', 'opportunity.won', 'opportunity.lost', 'opportunity.reopened', 'task.created', 'task.completed', 'task.cancelled', 'task.reopened', 'meeting.scheduled', 'meeting.rescheduled', 'meeting.completed', 'meeting.cancelled', 'meeting.reopened', 'note.added'])), name='timeline_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='timelineentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('kind__in', ('lead.created', 'lead.status_changed', 'lead.reassigned', 'lead.archived', 'lead.restored')), ('opportunity__isnull', True)), models.Q(('activity__isnull', True), ('kind__in', ('opportunity.created', 'opportunity.stage_changed', 'opportunity.won', 'opportunity.lost', 'opportunity.reopened')), ('opportunity__isnull', False)), models.Q(('activity__isnull', False), ('kind__in', ('task.created', 'task.completed', 'task.cancelled', 'task.reopened', 'meeting.scheduled', 'meeting.rescheduled', 'meeting.completed', 'meeting.cancelled', 'meeting.reopened', 'note.added'))), _connector='OR'), name='timeline_subject_matches_kind'),
        ),
    ]
