# Generated by Django 5.2.17 on 2026-10-03 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_backfill_timeline'),
        ('leads', '0004_id_owner_key'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('owner'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_owner_when_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_when_idx'),
        ),
    ]
