# Phase 4 review fixes: D-2 (timeline entries bound to their activity's opportunity and
# type), D-3 (meeting duration as an absolute interval), D-6 (visible text required).
# Generated by Django 5.2.17 on 2026-10-03 09:21

import datetime
import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.lookups
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_schedule_indexes'),
        ('leads', '0004_id_owner_key'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rewrites the table (new stored generated columns) and rebuilds indexes: lift the
        # statement timeout for this migration's own transaction (as 0003 does).
        migrations.RunSQL(sql="SET LOCAL statement_timeout = 0;", reverse_sql="SET LOCAL statement_timeout = 0;"),
        # Phase 4 review (D-2): the timeline's key onto its activity now also compares the
        # opportunity and the type, so it targets a wider unique key; the old one goes.
        migrations.RunSQL(
            sql="ALTER TABLE activities_timeline_entry DROP CONSTRAINT activities_timeline_activity_lead_fk;",
            reverse_sql=(
                "ALTER TABLE activities_timeline_entry ADD CONSTRAINT activities_timeline_activity_lead_fk"
                " FOREIGN KEY (activity_id, lead_id) REFERENCES activities_activity (id, lead_id);"
            ),
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='activities_activity_title_matches_type',
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='activities_activity_note_has_body',
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='activities_activity_meeting_times',
        ),
        migrations.RemoveConstraint(
            model_name='activity',
            name='activities_activity_id_lead_key',
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('opportunity_id'), models.Value(uuid.UUID('00000000-0000-0000-0000-000000000000'))), output_field=models.UUIDField()),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='opportunity_key',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Coalesce(models.F('opportunity_id'), models.Value(uuid.UUID('00000000-0000-0000-0000-000000000000'))), output_field=models.UUIDField()),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='subject_type',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(activity__isnull=False, then=models.Func(models.F('kind'), models.Value('.'), models.Value(1), function='split_part', output_field=models.CharField())), default=None), output_field=models.CharField(max_length=16, null=True)),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('title', ''), ('type', 'note')), models.Q(models.Q(('type', 'note'), _negated=True), ('title__regex', '\\S')), _connector='OR'), name='activities_activity_title_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'note'), _negated=True), ('description__regex', '\\S'), _connector='OR'), name='activities_activity_note_has_body'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_at__gt', models.F('starts_at')), ('ends_at__isnull', False), ('starts_at__isnull', False), ('type', 'meeting')), models.Q(models.Q(('type', 'meeting'), _negated=True), ('ends_at__isnull', True), ('starts_at__isnull', True)), _connector='OR'), name='activities_activity_meeting_times'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=django.db.models.lookups.LessThanOrEqual(models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('ends_at'), '-', models.F('starts_at')), output_field=models.DurationField()), datetime.timedelta(days=1)), name='activities_activity_meeting_duration'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(fields=('id', 'lead', 'opportunity_key', 'type'), name='activities_activity_timeline_key'),
        ),
        migrations.RunSQL(
            sql=(
                "ALTER TABLE activities_timeline_entry ADD CONSTRAINT activities_timeline_activity_fk"
                " FOREIGN KEY (activity_id, lead_id, opportunity_key, subject_type)"
                " REFERENCES activities_activity (id, lead_id, opportunity_key, type);"
            ),
            reverse_sql="ALTER TABLE activities_timeline_entry DROP CONSTRAINT activities_timeline_activity_fk;",
        ),
    ]
