# Phase 4 performance review: F1 (organisation-wide sort column, extended statistics),
# F3 (a lead's activities by due/start), F8 (ascending organisation-wide created index).
# Generated by Django 5.2.17 on 2026-10-03 09:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_review_integrity'),
        ('leads', '0004_id_owner_key'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rewrites the table (new stored generated columns) and rebuilds indexes: lift the
        # statement timeout for this migration's own transaction (as 0003 does).
        migrations.RunSQL(sql="SET LOCAL statement_timeout = 0;", reverse_sql="SET LOCAL statement_timeout = 0;"),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='activity',
            name='activities_lead_idx',
        ),
        migrations.AddField(
            model_name='activity',
            name='created_sort',
            field=models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(models.F('created_at'), output_field=models.DateTimeField()), output_field=models.DateTimeField()),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('created_sort'), models.F('id'), name='activities_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('lead'), models.F('schedule_sort'), models.F('id'), name='activities_lead_idx'),
        ),
        # Phase 4 review (P1): owners, types and statuses are far from independent (one owner
        # can hold a tenth of the rows; a rare status for one is common for another). Without
        # multi-column statistics the planner misjudged rare combinations by orders of magnitude
        # (500 ms -> 5 ms for "tasks, cancelled" of a user who never cancels).
        migrations.RunSQL(
            sql=[
                "CREATE STATISTICS activities_owner_type_status_stats (mcv, dependencies)"
                " ON owner_id, type, status FROM activities_activity;",
                "ALTER STATISTICS activities_owner_type_status_stats SET STATISTICS 1000;",
                "CREATE STATISTICS activities_type_status_stats (mcv, dependencies)"
                " ON type, status FROM activities_activity;",
            ],
            reverse_sql=[
                "DROP STATISTICS IF EXISTS activities_type_status_stats;",
                "DROP STATISTICS IF EXISTS activities_owner_type_status_stats;",
            ],
        ),
    ]
