# Phase 4 performance review at 2M activities: current work and one type's activities in
# schedule order without filtering past the closed history.
# Generated by Django 5.2.17 on 2026-10-03 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_review_performance'),
        ('leads', '0004_id_owner_key'),
        ('pipeline', '0004_id_lead_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Index builds over the whole table: lift the statement timeout for this migration's
        # own transaction (as 0003, 0005 and 0006 do).
        migrations.RunSQL(sql="SET LOCAL statement_timeout = 0;", reverse_sql="SET LOCAL statement_timeout = 0;"),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('owner'), models.F('type'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_owner_type_when_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('owner'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True), ('status__in', ('open', 'scheduled'))), name='activities_owner_current_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('type'), models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True)), name='activities_type_when_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(models.F('schedule_sort'), models.F('id'), condition=models.Q(('archived_at__isnull', True), ('status__in', ('open', 'scheduled'))), name='activities_current_idx'),
        ),
    ]
