# Phase 7: global search matches a task's title, a meeting's title and location, and a note's
# body (activities.models.SEARCH_TEXT) with a case-insensitive substring; one trigram index
# per type serves it in every workspace (docs/search.md#indexes has the plans before and
# after, the build times and the sizes). The owner is each index's first column, so one
# person's workspace looks up only their records: a GIN index on a uuid needs btree_gin, a
# contrib extension PostgreSQL marks trusted (the database owner can create it; kept on
# rollback, like pg_trgm).
#
# Built CONCURRENTLY, so activity reads and writes go on throughout (a plain CREATE INDEX
# holds a SHARE lock: every write on the table would wait for the whole build, about a
# minute for the note index at 2,000,000 activities). CONCURRENTLY can't run in a
# transaction, so the migration isn't atomic and lifts the timeouts for its session (not SET
# LOCAL), restoring them at the end in either direction (as leads.0005). If a build fails
# part-way, PostgreSQL leaves an INVALID index behind: drop it and run the migration again.
# Generated by Django 5.2.17 on 2026-10-03 18:04

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.conf import settings
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

LIFT = "SET statement_timeout = 0; SET lock_timeout = 0;"
RESTORE = "RESET statement_timeout; RESET lock_timeout;"


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('activities', '0007_current_work_indexes'),
        ('leads', '0006_leads_autovacuum'),
        ('pipeline', '0005_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(sql=LIFT, reverse_sql=RESTORE),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS btree_gin", reverse_sql=migrations.RunSQL.noop
        ),
        AddIndexConcurrently(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(models.F('owner'), django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('title'), name='gin_trgm_ops'), condition=models.Q(('archived_at__isnull', True), ('type', 'task')), name='activities_task_search_trgm'),
        ),
        AddIndexConcurrently(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(models.F('owner'), django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper(django.db.models.functions.text.Concat('title', models.Value(' '), 'location')), name='gin_trgm_ops'), condition=models.Q(('archived_at__isnull', True), ('type', 'meeting')), name='activities_meeting_search_trgm'),
        ),
        AddIndexConcurrently(
            model_name='activity',
            index=django.contrib.postgres.indexes.GinIndex(models.F('owner'), django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), condition=models.Q(('archived_at__isnull', True), ('type', 'note')), name='activities_note_search_trgm'),
        ),
        migrations.RunSQL(sql=RESTORE, reverse_sql=LIFT),
    ]
