# Generated by Django 5.2.17 on 2026-10-04 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activities_autovacuum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='edited_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=200)),
                ('extension', models.CharField(max_length=8)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('storage_key', models.CharField(max_length=200, unique=True)),
                ('state', models.CharField(choices=[('uploading', 'Uploading'), ('stored', 'Stored'), ('failed', 'Failed')], default='uploading', max_length=16)),
                ('scan_status', models.CharField(choices=[('not_scanned', 'Not scanned'), ('pending', 'Being checked'), ('clean', 'Clean'), ('rejected', 'Blocked')], default='not_scanned', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stored_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='activities.activity')),
                ('uploaded_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities_attachment',
                'indexes': [models.Index(models.F('note'), models.F('created_at'), condition=models.Q(('deleted_at__isnull', True)), name='activities_attachment_note_idx'), models.Index(models.F('created_at'), condition=models.Q(('state', 'uploading'), ('scan_status', 'pending'), models.Q(('purged_at__isnull', True), models.Q(('deleted_at__isnull', False), ('state', 'failed'), ('scan_status', 'rejected'), _connector='OR')), _connector='OR'), name='activities_attachment_open_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('state__in', ['uploading', 'stored', 'failed'])), name='activities_attachment_state'), models.CheckConstraint(condition=models.Q(('scan_status__in', ['not_scanned', 'pending', 'clean', 'rejected'])), name='activities_attachment_scan_status'), models.CheckConstraint(condition=models.Q(('size__gt', 0), ('size__lte', 104857600)), name='activities_attachment_size'), models.CheckConstraint(condition=models.Q(('sha256__regex', '^[0-9a-f]{64}$')), name='activities_attachment_sha256'), models.CheckConstraint(condition=models.Q(models.Q(('original_name', ''), _negated=True), ('extension__regex', '^[a-z0-9]{1,8}$')), name='activities_attachment_name'), models.CheckConstraint(condition=models.Q(('stored_at__isnull', True), models.Q(('state', 'uploading'), _negated=True), _connector='OR'), name='activities_attachment_stored_at'), models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('deleted_by__isnull', True)), ('deleted_at__isnull', False), _connector='OR'), name='activities_attachment_deleted'), models.CheckConstraint(condition=models.Q(('purged_at__isnull', True), ('deleted_at__isnull', False), ('state', 'failed'), ('scan_status', 'rejected'), _connector='OR'), name='activities_attachment_purged_only_when_gone')],
            },
        ),
    ]
