# Generated by Django 5.2.17 on 2026-10-10 15:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models

from arkray.core.migrations._reverse_guard import RefuseReverse


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(choices=[('lead', 'Customer (lead)'), ('user', 'Staff member (user)')], max_length=8)),
                ('subject_id', models.UUIDField()),
                ('reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ready', 'Ready to download'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('storage_key', models.CharField(blank=True, default='', max_length=200)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('files_included', models.PositiveIntegerField(default=0)),
                ('files_omitted', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('requested_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'privacy_data_export',
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='privacy_export_requester_idx'), models.Index(condition=models.Q(('status', 'ready')), fields=['expires_at'], name='privacy_export_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('subject_type__in', ['lead', 'user'])), name='privacy_export_subject'), models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'ready', 'failed', 'expired'])), name='privacy_export_status'), models.CheckConstraint(condition=models.Q(('reference', ''), _negated=True), name='privacy_export_reference_present'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'ready'), _negated=True), models.Q(('expires_at__isnull', False), models.Q(('storage_key', ''), _negated=True)), _connector='OR'), name='privacy_export_ready_complete')],
            },
        ),
        RefuseReverse(
            "privacy.0001_data_exports",
            loses="the record of every data export (who exported whose data, when)",
        ),
    ]
